extern const GeoLayout turning_platform_geo[];
extern u8 turning_platform_cobbled_deepslate_2_ci4[];
extern u8 turning_platform_cobbled_deepslate_2_pal_rgba16[];
extern u8 turning_platform_tex1_128x128_4fd3de01ff47bb46_14_ci8[];
extern u8 turning_platform_tex1_128x128_4fd3de01ff47bb46_14_pal_rgba16[];
extern Vtx turning_platform_Cube_mesh_layer_1_vtx_0[24];
extern Gfx turning_platform_Cube_mesh_layer_1_tri_0[];
extern Vtx turning_platform_Cube_mesh_layer_1_vtx_1[74];
extern Gfx turning_platform_Cube_mesh_layer_1_tri_1[];
extern Gfx mat_turning_platform_f3dlite_material_001[];
extern Gfx mat_revert_turning_platform_f3dlite_material_001[];
extern Gfx mat_turning_platform_f3dlite_material[];
extern Gfx mat_revert_turning_platform_f3dlite_material[];
extern Gfx turning_platform_Cube_mesh_layer_1[];
